dist: xenial
sudo: false

language: node_js
node_js:
  - "12"

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - ng lint
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - npm run-script build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/restaurant-booking
  on:
    branch: master