dist: xenial
sudo: false

language: node_js
node_js:
  - "12"

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - ng lint
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - npm run-script build

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "1//03aR-0N2Zs8hsCgYIARAAGAMSNwF-L9IrI_jFwEC8gbhC1O8Idol64yuAIP4s4UgeVcN8lr_tSlK0ffMvpTx0I-ga1jccSq0g4u4"
  on:
    branch: master